version: "3.8"

services:

app:
  image: shatynska/nextjs:1
  volumes:
    - ${APP_PATH}/${APP_DOMAIN}/${APP_FOLDER}/:/var/www/${APP_DOMAIN}
    - ${APP_PATH}/${APP_DOMAIN}/${APP_FOLDER}/current/_docker/nginx/conf.d:/etc/nginx/conf.d
    - /var/www/traefik/certs:/etc/certs:ro
  working_dir: /var/www/${APP_DOMAIN}/current
  labels:
    - "traefik.enable=true"
    - "traefik.docker.network=traefik-public"
    - "traefik.http.routers.${APP_FOLDER}_${APP_NAME}.entrypoints=https"
    - "traefik.http.routers.${APP_FOLDER}_${APP_NAME}.rule=Host(`shatynska.app.localhost`)"
    - "traefik.http.routers.${APP_FOLDER}_${APP_NAME}.tls=true"
    - "traefik.http.services.${APP_FOLDER}_${APP_NAME}.loadbalancer.server.port=3000"
  ports:
    - 3000:3000
  networks:
    - traefik-public
    - default

networks:
  traefik-public:
    external: true
  default:
