version: '3.8'

services:
  shatynska-com:
    image: shatynska/shatynskacom:latest
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-public'
      - 'traefik.http.routers.shatynska_com.entrypoints=https'
      - 'traefik.http.routers.shatynska_com.rule=Host(`shatynska.com`)'
      - 'traefik.http.routers.shatynska_com.tls=true'
      - 'traefik.http.routers.shatynska_com.tls.certresolver=letsEncrypt'
      - 'traefik.http.services.shatynska_com.loadbalancer.server.port=3000'
    ports:
      - 2990:3000
    networks:
      - traefik-public
      - default

networks:
  traefik-public:
    external: true
  default:
