version: "3.8"

services:
  app4:
    image: shatynska/shatynskacom:latest
    volumes:
      - /var/www/shatynska.com/green/current/_docker/nginx/conf.d:/etc/nginx/conf.ds
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.green_shatynska_com.entrypoints=https"
      - "traefik.http.routers.green_shatynska_com.rule=Host(`shatynska.com`)"
      - "traefik.http.routers.green_shatynska_com.tls=true"
      - "traefik.http.services.green_shatynska_com.loadbalancer.server.port=3000"
    ports:
      - 3000:3000
    networks:
      - traefik-public
      - default

  postgresql:
    image: postgres:15
    restart: always
    volumes:
      - /var/www/shatynska.com/tmp/db:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    labels:
      - traefik.enable=false
    networks:
      - traefik-public
      - default

networks:
  traefik-public:
    external: true
  default:
