name: Deploy

on:
  push:
    branches: [main]

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: shatynska/shatynskacom:latest

  redeploy:
    name: Redeploy stack to Portainer
    runs-on: ubuntu-latest
    needs: build-container
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Redeploy stack
        uses: luminos-company/portami@v1.1
        with:
          endpoint: "https://admin.psypra.com"
          access_token: ${{ secrets.PORTAINER_ACCESS_TOKEN }}
          stack_id: "shatynska_com"
          file_path: ".github/stack/production.yml"
          prune: true
          pull: true
